# Generated by Django 6.0.1 on 2026-08-05 15:24

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tasks.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_type', models.CharField(choices=[('FULLTIME', 'Full-time'), ('PARTTIME', 'Part-time'), ('INTERN', 'Intern')], default='FULLTIME', max_length=10)),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('salary', 'Salary')], default='hourly', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_per_period', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_hired', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.position')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[tasks.models.validate_half_hour])),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[tasks.models.validate_half_hour])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_start', models.DateField(blank=True, null=True)),
                ('payroll_period_end', models.DateField(blank=True, null=True)),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[tasks.models.validate_half_hour])),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[tasks.models.validate_half_hour])),
                ('sss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagibig', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employee')),
            ],
            options={
                'ordering': ['-payroll_period_start'],
                'unique_together': {('employee', 'payroll_period_start', 'payroll_period_end')},
            },
        ),
    ]
