# Generated by Django 6.0.1 on 2026-01-31 11:41

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[tasks.models.validate_half_hour]),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[tasks.models.validate_half_hour]),
        ),
    ]
