# Generated by Django 6.0.1 on 2026-08-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='jason', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='lopez', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default='bayot', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='employee_pics/'),
        ),
    ]
