# Generated by Django 6.0.1 on 2026-02-02 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_payroll_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_period',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
