# Generated by Django 6.0.1 on 2026-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_payroll_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_period',
            field=models.DateField(default=1995),
            preserve_default=False,
        ),
    ]
