# Generated by Django 6.0.1 on 2026-02-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_payroll_payroll_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='payroll_period',
        ),
    ]
