# Generated by Django 6.0.1 on 2026-02-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_employee_date_hired_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-payroll_period']},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'payroll_period')},
        ),
    ]
