# Generated by Django 6.0.1 on 2026-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_payroll_options_alter_payroll_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
